### PR TITLE
[Fix] default value for label color

### LINKED ISSUE #14: RequestError [HttpError]: Empty value for parameter 'color': undefined
## Steps to Reproduce

.github-labelsrc.json
```json
[
  {
    "name": "label",
    "description": ""
  }
]
```

```console
$ github-labels sync
RequestError [HttpError]: Empty value for parameter 'color': undefined
```

("@commercetools/github-labels": "1.0.2")

## Current Behavior

The "color" config field [marked optional](https://github.com/commercetools/github-labels/blob/master/readme.md#required-fields) are still required 

<details><summary>Full output: </summary>

```console
$ github-labels sync
RequestError [HttpError]: Empty value for parameter 'color': undefined
    at /Users/marina/Desktop/dev-projects/github/cogn-project-template/node_modules/@octokit/rest/plugins/validate/validate.js:66:15
    at Array.forEach (<anonymous>)
    at /Users/marina/Desktop/dev-projects/github/cogn-project-template/node_modules/@octokit/rest/plugins/validate/validate.js:38:12
    at Array.forEach (<anonymous>)
    at validate (/Users/marina/Desktop/dev-projects/github/cogn-project-template/node_modules/@octokit/rest/plugins/validate/validate.js:15:23)
    at processTicksAndRejections (internal/process/task_queues.js:89:5) {
  name: 'HttpError',
  status: 400,
  headers: undefined,
  request: {
    method: 'POST',
    baseUrl: 'https://api.github.com',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/16.28.2 Node.js/12.4.0 (macOS Mojave; x64)'
    },
    mediaType: { format: '', previews: [Array] },
    request: { hook: [Function: bound bound register], validate: [Object] },
    url: '/repos/:owner/:repo/labels',
    owner: 'CognitiveLaunchpad',
    repo: 'cogn-project-template',
    name: 'label',
    color: undefined,
    description: ''
  }
}

  GITHUB LABEL MANAGER

    Usage: ./bin/glm [command] [option]

      Commands:
        init        Initializes the label manager. It creates a new label-config.json
                    file with the current label data of your repository.

        sync        Uploads all changes you've made in the label-config.json file
                    into the repository to update the label with the given changes.
  
error Command failed with exit code 1.

```

</details>

## Possible Solution
Set defaut value for color

https://github.com/commercetools/github-labels/blob/1a695d3eb7e7be2c4cbb88d4abe43e1c88f0386e/lib/api.js#L46

(https://developer.github.com/v3/issues/labels/#create-a-label)

## Possible Implementation

```javascript
      color: label.color || 'ffffff',
```

### PR DESCRIPTION
**Pull request by TimonRey**
**This pull request:**
- closes #14

### CODE REVIEW

File: lib/api.js [hunk 1]
```diff
@@ -43,7 +43,7 @@ function createLabels(labels) {
       owner,
       repo,
       name: label.name,
-      color: label.color,
+      color: label.color || 'ffffff',
```
Comment (emmenko) [inline lib/api.js]: I think we should make this a required field instead, you would usually always want to specify the color yourself.

Comment (TimonRey) [reply lib/api.js]: Yes, I also think that's the better solution 👍 
116ce33
